import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service",
};

const LAST_UPDATED = "April 17, 2026";

export default function TermsPage() {
  return (
    <>
      <h1>Terms of Service</h1>
      <p className="text-sm text-[#A8A89E]">Last updated: {LAST_UPDATED}</p>

      <h2>1. Acceptance of Terms</h2>
      <p>
        By accessing or using Hygge (the &ldquo;Service&rdquo;), you agree to be bound by these Terms of Service.
        If you do not agree, do not use the Service.
      </p>

      <h2>2. Description of Service</h2>
      <p>
        Hygge is an AI-powered persona evaluation platform that generates synthetic-user feedback on products,
        ideas, and topics. Outputs are generated by large language models and are provided for research and
        decision-support purposes only. They are not a substitute for real user research, legal advice, medical
        advice, or any other professional counsel.
      </p>

      <h2>3. Accounts</h2>
      <p>
        You are responsible for maintaining the confidentiality of your account credentials. You must provide a
        valid email address and are responsible for all activity under your account.
      </p>

      <h2>4. Acceptable Use</h2>
      <p>You agree not to:</p>
      <ul>
        <li>Use the Service to generate content that is illegal, defamatory, harassing, or infringes third-party rights.</li>
        <li>Attempt to reverse engineer, probe, or disrupt the Service or its underlying infrastructure.</li>
        <li>Use automated scraping to circumvent rate limits or plan quotas.</li>
        <li>Submit content that contains personal data you do not have the right to process.</li>
      </ul>

      <h2>5. Plans and Billing</h2>
      <p>
        Paid plans (Pro, Max) are billed in advance through Stripe. You may cancel at any time; your plan will
        remain active until the end of the current billing period, and monthly evaluation quotas do not roll over.
        Bring-Your-Own-Key (BYOK) users are responsible for any usage charges from their chosen model provider.
      </p>

      <h2>6. Your Content</h2>
      <p>
        You retain all rights to the input you submit (&ldquo;User Content&rdquo;). By submitting User Content, you
        grant Hygge a worldwide, non-exclusive license to process it for the sole purpose of generating and
        storing evaluation outputs in your account.
      </p>

      <h2>7. AI-Generated Output</h2>
      <p>
        AI-generated outputs may contain inaccuracies, hallucinations, or biased statements. You are responsible for
        independently verifying any output before relying on it. Hygge makes no warranty that the output is
        accurate, complete, or fit for a particular purpose.
      </p>

      <h2>8. Third-Party Services</h2>
      <p>
        The Service uses third-party infrastructure including Supabase (database, storage, auth), Upstash (Redis),
        Stripe (payments), and one or more LLM providers (e.g., OpenAI-compatible endpoints, Anthropic, Google).
        Your use of the Service is also subject to those providers&rsquo; terms.
      </p>

      <h2>9. Termination</h2>
      <p>
        We may suspend or terminate your account for violation of these Terms, for non-payment, or to comply with
        legal requirements. You may delete your account at any time from the settings page.
      </p>

      <h2>10. Disclaimers</h2>
      <p>
        THE SERVICE IS PROVIDED &ldquo;AS IS&rdquo; WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
        INCLUDING BUT NOT LIMITED TO IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE,
        OR NON-INFRINGEMENT.
      </p>

      <h2>11. Limitation of Liability</h2>
      <p>
        TO THE MAXIMUM EXTENT PERMITTED BY LAW, HYGGE SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL,
        CONSEQUENTIAL, OR PUNITIVE DAMAGES. OUR AGGREGATE LIABILITY WILL NOT EXCEED THE AMOUNT YOU PAID TO US IN
        THE TWELVE MONTHS PRECEDING THE CLAIM.
      </p>

      <h2>12. Changes to These Terms</h2>
      <p>
        We may update these Terms from time to time. Material changes will be announced via email or in-app notice
        at least 14 days before they take effect.
      </p>

      <h2>13. Contact</h2>
      <p>
        Questions about these Terms can be sent to <a href="mailto:support@hygge.ai">support@hygge.ai</a>.
      </p>
    </>
  );
}
